#!/bin/sh -x
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication blockMesh -region solid
cp constant/solid/polyMesh/boundaryCoupled constant/solid/polyMesh/boundary
cat setSet.cmd | setSet -region solid
runApplication setsToZones -region solid -noFlipMap
rm log.blockMesh

runApplication blockMesh
cp constant/polyMesh/boundaryCoupled constant/polyMesh/boundary

runApplication chipAirCoolingSimpleFoam

if [ "$1" = "storeRef" ];
then
    rm -rf reference
    mkdir reference
    cp -r 1000 log.chipAirCoolingSimpleFoam reference
fi

runApplication checkReference -time 1000
