#!/bin/sh -x

cd tutorial1
./Allclean
./Allrun $1
cd ..

cd tutorial1_extendedHTC
./Allclean
./Allrun $1
cd ..

cd tutorial1_fineSolid
./Allclean
./Allrun $1
cd ..

cd tutorial1_noRadiation
./Allclean
./Allrun $1
cd ..

cd tutorial1_resistance
./Allclean
./Allrun $1
cd ..

cd tutorial1_twisted
./Allclean
./Allrun $1
cd ..

cd twoCavities
./Allclean
./Allrun $1
cd ..

cd cabin
./Allclean
./Allrun $1
cd ..

cd cabin_withRadiation
./Allclean
./Allrun $1
cd ..

cd cabin_withRadiation_noThinWall
./Allclean
./Allrun $1
cd ..

